name: Build, Test and Publish
on:
  push:
    tags:
      - 'release/*'
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build the packages
        run: dotnet build --configuration Release /p:PackageOutputPath=$GITHUB_WORKSPACE/artifacts
      - name: Publish the packages
        run: dotnet nuget push "$GITHUB_WORKSPACE/artifacts/*.nupkg" --source $ARTIFACTORY_PUSH_TARGET --api-key $API_KEY
        env:
          API_KEY: ${{ format('{0}:{1}', secrets.ARTIFACTORY_USERNAME, secrets.ARTIFACTORY_API_KEY) }}
          ARTIFACTORY_PUSH_TARGET: https://mdsol.jfrog.io/artifactory/api/nuget/nuget-local/mauth-client-dotnet
