name: Build and Test (.NET 6.0)
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Run the Core tests
        run: dotnet test $GITHUB_WORKSPACE/tests/Medidata.MAuth.CoreTests --framework net6.0
      - name: Run the ASP.NET Core tests
        run: dotnet test $GITHUB_WORKSPACE/tests/Medidata.MAuth.AspNetCoreTests --framework net6.0
